import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import HeaderPage from "@/components/HeaderPage";
import SubHeader from "@/components/SubHeader";
import Banner from "@/components/Banner";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <HeaderPage />
        <SubHeader />
        <Banner />
        {children}
      </body>
    </html>
  );
}
